### ISSUE TITLE
Publish on Open VSX?

### ISSUE THREAD

**Issue by atweiden** [kongeor/vsc-fennel#3]
Some editors, e.g. Onivim and VSCodium, source Code extensions from the Open VSX extension registry. It’d be great if this extension could be [published](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions) there too.

**Comment by kongeor** [comment]
That's a good idea. I'll handle this over the next couple of days.

**Comment by kongeor** [comment]
This has been published: https://open-vsx.org/extension/kongeor/vsc-fennel

It appears as unverified at the moment, but this should be resolved over the next few days.

Thank you for your suggestion.

**Comment by atweiden** [comment]
Thanks for that.
